/**
 * Language composable — supports English, Hindi, and Gujarati.
 * Persists preference in localStorage.
 */

export type Lang = 'en' | 'hi' | 'gu';

export interface LangOption {
  code: Lang;
  label: string;
  nativeLabel: string;
  flag: string;
}

export const LANGUAGES: LangOption[] = [
  { code: 'en', label: 'English',  nativeLabel: 'English', flag: '🇬🇧' },
  { code: 'hi', label: 'Hindi',    nativeLabel: 'हिन्दी',  flag: '🇮🇳' },
  { code: 'gu', label: 'Gujarati', nativeLabel: 'ગુજરાતી', flag: '🇮🇳' },
];

/* ── Translation dictionary ─────────────────────────────── */
const translations: Record<Lang, Record<string, string>> = {
  en: {
    home: 'Home',
    services: 'Services',
    search: 'Search',
    dashboard: 'Dashboard',
    chats: 'Chats',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    findService: 'Find a Service',
    searchPlaceholder: 'Search services...',
    heroTitle: 'Find Trusted Local Professionals',
    heroSubtitle: 'Connect with skilled service providers near you — fast, reliable, and vetted.',
    bookNow: 'Book Now',
    viewAll: 'View All Services',
    featuredServices: 'Featured Services',
    howItWorks: 'How It Works',
    topProviders: 'Top Providers',
    allCategories: 'All Categories',
    findServices: 'Find Services',
    browseCategory: 'Browse by Category',
    browseCategorySub: 'Choose from our wide range of professional services',
    howItWorksSteps: 'Get started in 3 simple steps',
    ctaTitle: 'Are You a Service Professional?',
    ctaSubtitle: 'Join our marketplace and start connecting with customers in your area. Get a free trial period to get started.',
    registerAsWorker: 'Register as Worker →',
    searchByLocation: 'Search by Location',
    findNearYou: 'Find service professionals near you',
    category: 'Category',
    radius: 'Radius (km)',
    keyword: 'Keyword',
    keywordPlaceholder: 'e.g. AC repair',
    searching: 'Searching...',
    myLocation: '📍 My Location',
    viewDetails: 'View Details',
    noResults: 'No services found nearby. Try increasing the search radius.',
    servicesCount: 'services',
    stepSearchTitle: 'Search',
    stepSearchDesc: 'Browse categories or search by location to find the right professional.',
    stepConnectTitle: 'Connect',
    stepConnectDesc: 'Chat directly with service providers and discuss your requirements.',
    stepReviewTitle: 'Review',
    stepReviewDesc: 'Leave a review after the job is done to help the community.',
    priceOnRequest: 'Price on request',
    noServicesFound: 'No services found. Check back soon!',
    previous: 'Previous',
    next: 'Next',
    locationInfoMsg: 'Services are linked to the worker\'s profile location. Workers set their area when setting up their profile — the search finds services offered by workers near your chosen area.',
    searchArea: 'Your Area / Location',
    areaPlaceholder: 'e.g. Ahmedabad, Vastrapur, Maninagar...',
    findArea: 'Find',
    usingLocation: 'Searching near',
    areaHidden: 'Location not shared',
    resultsNear: 'results near',
    noResultsTip: 'Try increasing the radius or searching a broader area.',
    enterAreaToSearch: 'Type your area name above and click Find, then hit Search.',
    pleaseSetLocation: 'Please enter and find an area first.',

    // Home & Search additions
    servicingLabel: 'Servicing',
    changeLabel: 'Change',
    heroTitlePre: 'Find Trusted Local Service',
    heroTitlePost: 'Professionals in',
    heroSubtitleNew: 'Connect with background-verified electricians, plumbers, AC technicians, and cleaners near you. Book doorstep service in 60 seconds.',
    allCategoriesOpt: 'All Categories',
    trendingLabel: 'Trending',
    viewAllCategories: 'View All Categories →',
    exploreServices: 'Explore Services →',
    verifiedPros: 'Verified Pros',
    verifiedTechsCount: 'Verified Technicians',
    avgServiceRating: 'Average Service Rating',
    citiesActive: 'Cities Active in India',
    avgResponseTime: 'Average Response Time',
    workerPartnershipProgram: 'Worker Partnership Program',
    expressServiceTitle: '2-Hour Express Service',
    expressServiceDesc: 'Guaranteed technician arrival within 120 mins',
    warrantyTitle: '30-Day Service Warranty',
    warrantyDesc: 'Free re-visit if you are not 100% satisfied',
    pricingTitle: 'Transparent Pricing',
    pricingDesc: 'Pre-approved rates with no hidden doorstep charges',
    searchTitle: 'Advanced Service Finder',
    searchSub: 'Find verified local professionals in your city with custom filters, ratings & distance.',
    locationLabel: 'Location:',
    clickToChange: '(Click to change)',
    searchBtnLabel: 'Search Services',
    popularSearches: 'Popular Searches:',
    categoryFilter: 'Category',
    priceFilter: 'Max Price',
    radiusFilter: 'Radius',
    ratingFilter: 'Minimum Rating',
    anyRating: 'Any Rating',
    topRated: '4.5★ & above (Top Rated)',
    aboveFour: '4.0★ & above',
    aboveThree: '3.5★ & above',
    searchPlaceholderInput: 'Search by service name, keyword or pro name...',
    customerReviews: 'Customer Reviews',
    sortBy: 'Sort Results By',
    relevance: 'Relevance',
    priceLowHigh: 'Price: Low to High',
    priceHighLow: 'Price: High to Low',
    ratingHighLow: 'Rating: High to Low',
    distanceNearFar: 'Distance: Near to Far',

    // Dashboard & Sidebar additions
    sidebarOverview: 'Dashboard Overview',
    sidebarMessages: 'My Messages',
    sidebarServices: 'My Offered Services',
    sidebarSaved: 'Saved Services',
    sidebarProfile: 'Profile & Password',
    sidebarNotifications: 'Notifications',
    sidebarSignOut: 'Sign Out',
    roleWorker: 'Service Provider',
    roleCustomer: 'Customer Account',
    offeredServicesTitle: 'My Offered Services',
    offeredServicesSub: 'Manage your active service listings and pricing rates',
    addNewService: 'Add New Service',
    trialBannerTitle: 'Free Trial Limit Reached',
    trialBannerDesc: 'You have used your free slots. Upgrade your subscription to publish unlimited services.',
    upgradePlan: 'Upgrade Plan',
    tabAll: 'All',
    tabPending: 'Pending',
    tabApproved: 'Approved',
    tabRejected: 'Rejected',
    pendingApprovalLabel: 'Pending Approval',
    editBtn: 'Edit',
    deleteBtn: 'Delete',
    noOfferedServices: 'No offered services found',
    noOfferedServicesDesc: 'Create your first service listing to start receiving customer leads.',
    createServiceTitle: 'Create New Service',
    createServiceSub: 'Add a new service listing to your worker profile',
    editServiceTitle: 'Edit Service',
    editServiceSub: 'Update your offered service listing and pricing rates',
    backToServices: 'Back to Services',
    selectCategory: 'Select category',
    minPrice: 'Min Price (₹)',
    maxPriceLabel: 'Max Price (₹)',
    serviceImageLabel: 'Service Image',
    uploadImage: 'Upload Image',
    uploadNewImage: 'Upload New Image',
    imageSizeTip: 'Recommended resolution: 800x600. Maximum size: 2MB.',
    cancelBtn: 'Cancel',
    createServiceBtn: 'Create Service',
    creatingServiceBtn: 'Creating...',
    saveChangesBtn: 'Save Changes',
    savingChangesBtn: 'Saving Changes...',
    liveVersionLabel: 'Live Approved Version',
    liveVersionDesc: 'This is what other customers currently see on the marketplace. It remains live while updates are pending.',
    proposedChangesLabel: 'Proposed Changes Awaiting Approval',
    proposedChangesRejected: 'Proposed Changes Were Rejected',
    title: 'Title',
    description: 'Description'
  },
  hi: {
    home: 'होम',
    services: 'सेवाएं',
    search: 'खोज',
    dashboard: 'डैशबोर्ड',
    chats: 'चैट',
    login: 'लॉगिन',
    register: 'रजिस्टर',
    logout: 'लॉगआउट',
    findService: 'सेवा खोजें',
    searchPlaceholder: 'सेवाएं खोजें...',
    heroTitle: 'विश्वसनीय स्थानीय पेशेवर खोजें',
    heroSubtitle: 'अपने नज़दीक कुशल सेवा प्रदाताओं से जुड़ें — तेज़, विश्वसनीय और सत्यापित।',
    bookNow: 'अभी बुक करें',
    viewAll: 'सभी सेवाएं देखें',
    featuredServices: 'विशेष सेवाएं',
    howItWorks: 'यह कैसे काम करता है',
    topProviders: 'शीर्ष प्रदाता',
    allCategories: 'सभी श्रेणियां',
    findServices: 'सेवाएं खोजें',
    browseCategory: 'श्रेणी के अनुसार ब्राउज़ करें',
    browseCategorySub: 'हमारी विस्तृत पेशेवर सेवाओं में से चुनें',
    howItWorksSteps: '3 आसान चरणों में शुरू करें',
    ctaTitle: 'क्या आप एक सेवा पेशेवर हैं?',
    ctaSubtitle: 'हमारे मार्केटप्लेस से जुड़ें और अपने क्षेत्र के ग्राहकों से जुड़ना शुरू करें।',
    registerAsWorker: 'कार्यकर्ता के रूप में रजिस्टर करें →',
    searchByLocation: 'स्थान के आधार पर खोजें',
    findNearYou: 'अपने नज़दीक सेवा प्रदाता खोजें',
    category: 'श्रेणी',
    radius: 'दायरा (कि.मी.)',
    keyword: 'कीवर्ड',
    keywordPlaceholder: 'जैसे: AC मरम्मत',
    searching: 'खोज रहे हैं...',
    myLocation: '📍 मेरा स्थान',
    viewDetails: 'विवरण देखें',
    noResults: 'नज़दीक कोई सेवा नहीं मिली। खोज दायरा बढ़ाएं।',
    servicesCount: 'सेवाएं',
    stepSearchTitle: 'खोज',
    stepSearchDesc: 'सही पेशेवर खोजने के लिए श्रेणियाँ ब्राउज़ करें या स्थान से खोजें।',
    stepConnectTitle: 'जुड़ें',
    stepConnectDesc: 'सेवा प्रदाताओं के साथ सीधे चैट करें और अपनी ज़रूरतें बताएं।',
    stepReviewTitle: 'समीक्षा',
    stepReviewDesc: 'काम पूरा होने के बाद समीक्षा छोड़ें और समुदाय की मदद करें।',
    priceOnRequest: 'कीमत पर अनुरोध',
    noServicesFound: 'कोई सेवा नहीं मिली। जल्द वापस आएं!',
    previous: 'पिछला',
    next: 'अगला',
    locationInfoMsg: 'सेवाएं कार्यकर्ता की प्रोफ़ाइल लोकेशन से जुड़ी होती हैं। कार्यकर्ता अपनी प्रोफ़ाइल में क्षेत्र सेट करते हैं — खोज आपके चुने क्षेत्र के पास मौजूद कार्यकर्ताओं की सेवाएं दिखाती है।',
    searchArea: 'आपका क्षेत्र / स्थान',
    areaPlaceholder: 'जैसे: अहमदाबाद, वस्त्रपुर, मणिनगर...',
    findArea: 'खोजें',
    usingLocation: 'खोज क्षेत्र',
    areaHidden: 'स्थान साझा नहीं',
    resultsNear: 'परिणाम नज़दीक',
    noResultsTip: 'दायरा बढ़ाएं या अलग क्षेत्र में खोजें।',
    enterAreaToSearch: 'ऊपर अपना क्षेत्र का नाम लिखें और खोजें पर क्लिक करें।',
    pleaseSetLocation: 'पहले कोई क्षेत्र खोजें।',

    // Home & Search additions
    servicingLabel: 'सेवाएं चालू हैं',
    changeLabel: 'बदलें',
    heroTitlePre: 'विश्वसनीय स्थानीय सेवा',
    heroTitlePost: 'पेशेवर खोजें',
    heroSubtitleNew: 'अपने नज़दीक सत्यापित इलेक्ट्रीशियन, प्लंबर, एसी तकनीशियन और क्लीनर से जुड़ें। 60 सेकंड में बुकिंग करें।',
    allCategoriesOpt: 'सभी श्रेणियां',
    trendingLabel: 'ट्रेंडिंग',
    viewAllCategories: 'सभी श्रेणियां देखें →',
    exploreServices: 'सेवाएं खोजें →',
    verifiedPros: 'सत्यापित विशेषज्ञ',
    verifiedTechsCount: 'सत्यापित तकनीशियन',
    avgServiceRating: 'औसत सेवा रेटिंग',
    citiesActive: 'भारत के सक्रिय शहर',
    avgResponseTime: 'औसत प्रतिक्रिया समय',
    workerPartnershipProgram: 'कार्यकर्ता साझेदारी कार्यक्रम',
    expressServiceTitle: '2-घंटे एक्सप्रेस सेवा',
    expressServiceDesc: '120 मिनट के भीतर तकनीशियन आगमन की गारंटी',
    warrantyTitle: '30-दिन सेवा वारंटी',
    warrantyDesc: '100% संतुष्ट न होने पर मुफ्त दोबारा सेवा',
    pricingTitle: 'पारदर्शी मूल्य निर्धारण',
    pricingDesc: 'बिना किसी छिपे शुल्क के पूर्व-स्वीकृत दरें',
    searchTitle: 'उन्नत सेवा खोजक',
    searchSub: 'कस्टम फ़िल्टर, रेटिंग और दूरी के साथ अपने शहर में सत्यापित स्थानीय पेशेवरों को खोजें।',
    locationLabel: 'स्थान:',
    clickToChange: '(बदलने के लिए क्लिक करें)',
    searchBtnLabel: 'सेवाएं खोजें',
    popularSearches: 'लोकप्रिय खोजें:',
    categoryFilter: 'श्रेणी',
    priceFilter: 'अधिकतम मूल्य',
    radiusFilter: 'दायरा',
    ratingFilter: 'न्यूनतम रेटिंग',
    anyRating: 'कोई भी रेटिंग',
    topRated: '4.5★ और ऊपर (शीर्ष रेटेड)',
    aboveFour: '4.0★ और ऊपर',
    aboveThree: '3.5★ और ऊपर',
    searchPlaceholderInput: 'सेवा का नाम, कीवर्ड या पेशेवर का नाम खोजें...',
    customerReviews: 'ग्राहक समीक्षाएं',
    sortBy: 'परिणामों को क्रमबद्ध करें',
    relevance: 'प्रासंगिकता',
    priceLowHigh: 'कीमत: कम से अधिक',
    priceHighLow: 'कीमत: अधिक से कम',
    ratingHighLow: 'रेटिंग: अधिक से कम',
    distanceNearFar: 'दूरी: पास से दूर',

    // Dashboard & Sidebar additions
    sidebarOverview: 'डैशबोर्ड अवलोकन',
    sidebarMessages: 'मेरे संदेश',
    sidebarServices: 'मेरी दी जाने वाली सेवाएं',
    sidebarSaved: 'सहेजी गई सेवाएं',
    sidebarProfile: 'प्रोफ़ाइल और पासवर्ड',
    sidebarNotifications: 'सूचनाएं',
    sidebarSignOut: 'साइन आउट',
    roleWorker: 'सेवा प्रदाता',
    roleCustomer: 'ग्राहक खाता',
    offeredServicesTitle: 'मेरी दी जाने वाली सेवाएं',
    offeredServicesSub: 'अपनी सक्रिय सेवा सूची और मूल्य निर्धारण दरों का प्रबंधन करें',
    addNewService: 'नई सेवा जोड़ें',
    trialBannerTitle: 'निःशुल्क परीक्षण सेवा सीमा समाप्त',
    trialBannerDesc: 'आप अपने मुफ्त स्लॉट का उपयोग कर चुके हैं। असीमित सेवाओं के लिए सदस्यता अपग्रेड करें।',
    upgradePlan: 'योजना अपग्रेड करें',
    tabAll: 'सभी',
    tabPending: 'लंबित',
    tabApproved: 'स्वीकृत',
    tabRejected: 'अस्वीकृत',
    pendingApprovalLabel: 'मंजूरी लंबित',
    editBtn: 'संपादित करें',
    deleteBtn: 'हटाएं',
    noOfferedServices: 'कोई दी जाने वाली सेवाएं नहीं मिलीं',
    noOfferedServicesDesc: 'ग्राहक लीड प्राप्त करना शुरू करने के लिए अपनी पहली सेवा सूची बनाएं।',
    createServiceTitle: 'नई सेवा बनाएं',
    createServiceSub: 'अपने कार्यकर्ता प्रोफ़ाइल में एक नई सेवा जोड़ें',
    editServiceTitle: 'सेवा संपादित करें',
    editServiceSub: 'अपनी दी जाने वाली सेवा सूची और दरों को अपडेट करें',
    backToServices: 'सेवाओं पर वापस जाएं',
    selectCategory: 'श्रेणी चुनें',
    minPrice: 'न्यूनतम मूल्य (₹)',
    maxPriceLabel: 'अधिकतम मूल्य (₹)',
    serviceImageLabel: 'सेवा छवि',
    uploadImage: 'छवि अपलोड करें',
    uploadNewImage: 'नई छवि अपलोड करें',
    imageSizeTip: 'अनुशंसित रिज़ॉल्यूशन: 800x600। अधिकतम आकार: 2MB।',
    cancelBtn: 'रद्द करें',
    createServiceBtn: 'सेवा बनाएं',
    creatingServiceBtn: 'बना रहे हैं...',
    saveChangesBtn: 'परिवर्तन सहेजें',
    savingChangesBtn: 'सहेज रहे हैं...',
    liveVersionLabel: 'सक्रिय स्वीकृत संस्करण',
    liveVersionDesc: 'यह वही है जो अन्य ग्राहक वर्तमान में मार्केटप्लेस पर देखते हैं।',
    proposedChangesLabel: 'मंजूरी की प्रतीक्षा में प्रस्तावित परिवर्तन',
    proposedChangesRejected: 'प्रस्तावित परिवर्तन अस्वीकार कर दिए गए',
    title: 'शीर्षक',
    description: 'विवरण'
  },
  gu: {
    home: 'હોમ',
    services: 'સેવાઓ',
    search: 'શોધ',
    dashboard: 'ડૅશબોર્ડ',
    chats: 'ચૅટ',
    login: 'લૉગિન',
    register: 'નોંધણી',
    logout: 'લૉગઆઉટ',
    findService: 'સેવા શોધો',
    searchPlaceholder: 'સેવાઓ શોધો...',
    heroTitle: 'વિશ્વસનીય સ્થાનિક વ્યાવસાયિકો શોધો',
    heroSubtitle: 'તમારી નજીક કૌશલ્યવાન સેવા પ્રદાતાઓ સાથે જોડાઓ — ઝડપી, વિશ્વસનીય અને ચકાસાયેલ.',
    bookNow: 'હવે બૂક કરો',
    viewAll: 'બધી સેવાઓ જુઓ',
    featuredServices: 'વિશેષ સેવાઓ',
    howItWorks: 'તે કેવી રીતે કામ કરે છે',
    topProviders: 'ટોચના પ્રદાતાઓ',
    allCategories: 'બધી શ્રેણીઓ',
    findServices: 'સેવાઓ શોધો',
    browseCategory: 'શ્રેણી દ્વારા બ્રાઉઝ કરો',
    browseCategorySub: 'અમારી વ્યાપક વ્યવસાયિક સેવાઓ માંથી પસંદ કરો',
    howItWorksSteps: '3 સરળ પગલામાં શરૂ કરો',
    ctaTitle: 'શું તમે સેવા વ્યાવસાયિક છો?',
    ctaSubtitle: 'અમારા માર્કેટપ્લેસ સાથે જોડાઓ અને તમારા વિસ્તારના ગ્રાહકો સાથે જોડાવા માંડો.',
    registerAsWorker: 'કામદાર તરીકે નોંધણી કરો →',
    searchByLocation: 'સ્થાન અનુસાર શોધ',
    findNearYou: 'તમારી નજીક સેવા વ્યાવસાયિકો શોધો',
    category: 'શ્રેણી',
    radius: 'ત્રિજ્યા (કિ.મી.)',
    keyword: 'કીવર્ડ',
    keywordPlaceholder: 'જેમ કે: AC રિપેર',
    searching: 'શોધ ચાલી રહી છે...',
    myLocation: '📍 મારું સ્થાન',
    viewDetails: 'વિગતો જુઓ',
    noResults: 'નજીકમાં કોઈ સેવા મળી નથી. શોધ ત્રિજ્યા વધારો.',
    servicesCount: 'સેવાઓ',
    stepSearchTitle: 'શોધ',
    stepSearchDesc: 'યોગ્ય વ્યાવસાયિક શોધવા માટે શ્રેણીઓ બ્રાઉઝ કરો અથવા સ્થાન દ્વારા શોધ કરો.',
    stepConnectTitle: 'જોડાઓ',
    stepConnectDesc: 'સેવા પ્રદાતાઓ સાથે સીધી ચૅટ કરો અને તમારી જરૂરિયાત સમજાવો.',
    stepReviewTitle: 'સમીક્ષા',
    stepReviewDesc: 'કામ પૂર્ણ થયા પછી સમીક્ષા લખો અને સમુદાયને મદદ કરો.',
    priceOnRequest: 'કિંમત વિનંતી પર',
    noServicesFound: 'કોઈ સેવા મળી નથી. ટૂંક સમયમાં ફરી તપાસો!',
    previous: 'પહેલાં',
    next: 'આગળ',
    locationInfoMsg: 'સેવાઓ કામદારની પ્રોફાઇલ સ્થાન સાથે જોડાયેલ છે. કામદારો પ્રોફાઇલ સેટ કરતી વખતે વિસ્તાર સેટ કરે છે — શોધ તમારા પસંદ કરેલ વિસ્તારની નજીકના કામદારોની સેવાઓ બતાવે છે.',
    searchArea: 'તમારો વિસ્તાર / સ્થાન',
    areaPlaceholder: 'દા.ત. અમદાવાદ, વસ્ત્રાપુર, મણિનગર...',
    findArea: 'શોધો',
    usingLocation: 'નજીક શોધ',
    areaHidden: 'સ્થાન શેર કર્યું નથી',
    resultsNear: 'પરિણામ નજીક',
    noResultsTip: 'ત્રિજ્યા વધારો અથવા અલગ વિસ્તારમાં શોધ કરો.',
    enterAreaToSearch: 'ઉપર તમારો વિસ્તાર લખો અને શોધો પર ક્લિક કરો.',
    pleaseSetLocation: 'પહેલાં કોઈ વિસ્તાર શોધો.',

    // Home & Search additions
    servicingLabel: 'આપણી સેવાઓ',
    changeLabel: 'બદલો',
    heroTitlePre: 'વિશ્વસનીય સ્થાનિક સેવા',
    heroTitlePost: 'વ્યાવસાયિકો',
    heroSubtitleNew: 'તમારી નજીક ચકાસાયેલ ઇલેક્ટ્રિશિયન, પ્લમ્બર, એસી ટેકનિશિયન અને ક્લીનર્સ શોધો. 60 સેકન્ડમાં બુક કરો.',
    allCategoriesOpt: 'બધી શ્રેણીઓ',
    trendingLabel: 'ટ્રેન્ડિંગ',
    viewAllCategories: 'બધી શ્રેણીઓ જુઓ →',
    exploreServices: 'સેવાઓ જુઓ →',
    verifiedPros: 'ચકાસાયેલ નિષ્ણાતો',
    verifiedTechsCount: 'ચકાસાયેલ ટેકનિશિયન',
    avgServiceRating: 'સરેરાશ સેવા રેટિંગ',
    citiesActive: 'ભારતમાં સક્રિય શહેરો',
    avgResponseTime: 'સરેરાશ પ્રતિભાવ સમય',
    workerPartnershipProgram: 'કામદાર ભાગીદારી કાર્યક્રમ',
    expressServiceTitle: '2-કલાક એક્સપ્રેસ સેવા',
    expressServiceDesc: '120 મિનિટમાં ટેકનિશિયન આગમનની ખાતરી',
    warrantyTitle: '30-દિવસની સેવા વોરંટી',
    warrantyDesc: 'જો તમે 100% સક્રિય ન હોવ તો મફત ફરી મુલાકાત',
    pricingTitle: 'પારદર્શક કિંમત નિર્ધારણ',
    pricingDesc: 'કોઈપણ છુપા ચાર્જ વગર અગાઉથી મંજૂર કિંમતો',
    searchTitle: 'અદ્યતન સેવા શોધક',
    searchSub: 'કસ્ટમ ફિલ્ટર્સ, રેટિંગ્સ અને અંતર સાથે તમારા શહેરમાં ચકાસાયેલ વ્યાવસાયિકો શોધો.',
    locationLabel: 'સ્થાન:',
    clickToChange: '(બદલવા માટે ક્લિક કરો)',
    searchBtnLabel: 'સેવાઓ શોધો',
    popularSearches: 'લોકપ્રિય શોધો:',
    categoryFilter: 'શ્રેણી',
    priceFilter: 'મહત્તમ કિંમત',
    radiusFilter: 'ત્રિજ્યા',
    ratingFilter: 'ન્યૂનતમ રેટિંગ',
    anyRating: 'કોઈપણ રેટિંગ',
    topRated: '4.5★ અને તેથી વધુ (ટોચના રેટેડ)',
    aboveFour: '4.0★ અને તેથી વધુ',
    aboveThree: '3.5★ અને તેથી વધુ',
    searchPlaceholderInput: 'સેવાનું નામ, કીવર્ડ અથવા વ્યાવસાયિકનું નામ શોધો...',
    customerReviews: 'ગ્રાહક સમીક્ષાઓ',
    sortBy: 'પરિણામો ક્રમબદ્ધ કરો',
    relevance: 'સુસંગતતા',
    priceLowHigh: 'કિંમત: ઓછી થી વધુ',
    priceHighLow: 'કિંમત: વધુ થી ઓછી',
    ratingHighLow: 'રેટિંગ: વધુ થી ઓછી',
    distanceNearFar: 'અંતર: નજીક થી દૂર',

    // Dashboard & Sidebar additions
    sidebarOverview: 'ડૅશબોર્ડ વિહંગાવલોકન',
    sidebarMessages: 'મારા સંદેશાઓ',
    sidebarServices: 'મારી ઓફર કરેલી સેવાઓ',
    sidebarSaved: 'સાચવેલી સેવાઓ',
    sidebarProfile: 'પ્રોફાઇલ અને પાસવર્ડ',
    sidebarNotifications: 'સૂચનાઓ',
    sidebarSignOut: 'સાઇન આઉટ',
    roleWorker: 'સેવા પ્રદાતા',
    roleCustomer: 'ગ્રાહક ખાતું',
    offeredServicesTitle: 'મારી ઓફર કરેલી સેવાઓ',
    offeredServicesSub: 'તમારી સક્રિય સેવા સૂચિઓ અને કિંમત દરોનું સંचાલન કરો',
    addNewService: 'નવી સેવા ઉમેરો',
    trialBannerTitle: 'મફત અજમાયશ સેવા મર્યાદા પૂર્ણ થઈ',
    trialBannerDesc: 'તમે તમારા મફત સ્લોટનો ઉપયોગ કર્યો છે. અમર્યાદિત સેવાઓ માટે સબ્સ્ક્રિપ્શન અપગ્રેડ કરો.',
    upgradePlan: 'પ્લાન અપગ્રેડ કરો',
    tabAll: 'બધું',
    tabPending: 'બાકી',
    tabApproved: 'મંજૂર',
    tabRejected: 'અસ્વીકૃત',
    pendingApprovalLabel: 'મંજૂરી બાકી',
    editBtn: 'ફેરફાર કરો',
    deleteBtn: 'કાઢી નાખો',
    noOfferedServices: 'કોઈ ઓફર કરેલી સેવાઓ મળી નથી',
    noOfferedServicesDesc: 'ગ્રાહક લીડ્સ મેળવવાનું શરૂ કરવા માટે તમારી પ્રથમ સેવા સૂચિ બનાવો.',
    createServiceTitle: 'નવી સેવા બનાવો',
    createServiceSub: 'તમારી પ્રોફાઇલમાં નવી સેવા ઉમેરો',
    editServiceTitle: 'સેવા સંપાદિત કરો',
    editServiceSub: 'તમારી સેવા સૂચિ અને કિંમત દરો અપડેટ કરો',
    backToServices: 'સેવાઓ પર પાછા જાઓ',
    selectCategory: 'શ્રેણી પસંદ કરો',
    minPrice: 'ન્યૂનતમ કિંમત (₹)',
    maxPriceLabel: 'મહત્તમ કિંમત (₹)',
    serviceImageLabel: 'સેવા છબી',
    uploadImage: 'છબી અપલોડ કરો',
    uploadNewImage: 'નવી છબી અપલોડ કરો',
    imageSizeTip: 'ભલામણ કરેલ રિઝોલ્યુશન: 800x600. મહત્તમ કદ: 2MB.',
    cancelBtn: 'રદ કરો',
    createServiceBtn: 'સેવા બનાવો',
    creatingServiceBtn: 'બનાવી રહ્યા છીએ...',
    saveChangesBtn: 'ફેરફાર સાચવો',
    savingChangesBtn: 'સાચવી રહ્યા છીએ...',
    liveVersionLabel: 'લાઇવ મંજૂર સંસ્કરણ',
    liveVersionDesc: 'આ તે છે જે અન્ય ગ્રાહકો હાલમાં માર્કેટપ્લેસ પર જુએ છે.',
    proposedChangesLabel: 'મંજૂરીની રાહ જોઈ રહેલા પ્રસ્તાવિત ફેરફારો',
    proposedChangesRejected: 'પ્રસ્તાવિત ફેરફારો અસ્વીકાર કરવામાં આવ્યા',
    title: 'શીર્ષક',
    description: 'વર્ણન'
  },
};

/* ── Composable ─────────────────────────────────────────── */
export const useLanguage = () => {
  const currentLang = useState<Lang>('app-lang', () => 'en');

  const setLang = (code: Lang) => {
    if (import.meta.server) return;
    currentLang.value = code;
    localStorage.setItem('lang', code);
    document.documentElement.lang = code === 'en' ? 'en' : code === 'hi' ? 'hi-IN' : 'gu-IN';
  };

  const initLang = () => {
    if (import.meta.server) return;
    const saved = localStorage.getItem('lang') as Lang | null;
    const lang: Lang = saved && ['en', 'hi', 'gu'].includes(saved) ? saved : 'en';
    currentLang.value = lang;
    document.documentElement.lang = lang === 'en' ? 'en' : lang === 'hi' ? 'hi-IN' : 'gu-IN';
  };

  const t = (key: string): string => {
    return translations[currentLang.value]?.[key] ?? translations['en'][key] ?? key;
  };

  const currentLangOption = computed(() =>
    LANGUAGES.find(l => l.code === currentLang.value) ?? LANGUAGES[0]
  );

  return { currentLang, currentLangOption, setLang, initLang, t, LANGUAGES };
};
